(GH-10) Added Twitter Stats
oss-stats/oss-stats pull request #14
Opened 2017-04-09 19:10 UTC by gep13

2017-04-09 19:42 UTC, gep13 commented
Fixes #10

2017-04-11 07:43 UTC, devlead requested changes

2017-04-11 07:43 UTC, devlead commented on TwitterStats/run.ps1
> +                        $Parameters.Keys | % { $HTTPEndpoint = $HTTPEndpoint + $_  +'='+ [System.Net.WebUtility]::UrlEncode($Parameters.Item($_)).Replace('+','%20') + '&'}
`[System.Net.WebUtility]::UrlEncode` can be replaced with `[Uri]::EscapeDataString`, then no replace is needed and also ensures compat with PowerShell core.

2017-04-11 07:43 UTC, devlead commented on TwitterStats/run.ps1
> +                                        'PartitionKey'      = [Guid]::NewGuid().ToString("n")
Should use `$partitionKey`

2017-04-11 07:46 UTC, gep13 commented on TwitterStats/run.ps1
> +                        $Parameters.Keys | % { $HTTPEndpoint = $HTTPEndpoint + $_  +'='+ [System.Net.WebUtility]::UrlEncode($Parameters.Item($_)).Replace('+','%20') + '&'}
@devlead good catch.  I borrowed this function directly.  I have made the suggested change.

2017-04-11 07:58 UTC, gep13 commented on TwitterStats/run.ps1
> +                                        'PartitionKey'      = [Guid]::NewGuid().ToString("n")
Done.

2017-04-11 07:59 UTC, devlead approved these changes

2017-04-11 08:05 UTC, merged